#!/bin/csh
#
echo  perform PDDG/PM3 optimization
echo      include GB/SA
#
# usage - xPDGGBOPT moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]} optzmat
csh PDGGBOPTcmd >& log
echo  output is in out, sum and plt.pdb
rm optzmat
#
exit
