#!/usr/bin/env bash

set -e

readonly progname=$(basename $0)
readonly progdir=$(readlink -m $(dirname $0))
readonly args="$@"
readonly workingd="$PWD"


main ()
{
	fc-cache -v &&  mkfontscale &&  mkfontdir
}

main

exit $?
