#!/usr/bin/env bash

readonly ARGS="$@"
readonly MPLAYER="$( which mplayer )"
readonly OPTIONS="-vo fbdev2 -fs -zoom -x 683 -y 384 -quiet" 
#readonly OPTIONS="-vo fbdev2 -quiet" 

main() 
{
    "$MPLAYER" $OPTIONS "$ARGS"
}

main
