#!/usr/bin/env bash
# move files to ~/.Trash instead of sending into a black hole
# rm is aliased to this
date="$( date +%F )"
files="$@"
if [[ -z "$files" ]]
then
	echo "usage: trash <files>"
else
	[[ ! -d "${HOME}/.Trash/${date}" ]]	&& mkdir -p "${HOME}/.Trash/${date}"
	for f in ${files}
	do
		mv -fv "${f}" "${HOME}/.Trash/${date}/"
	done
	echo "(trashcan is ~/.Trash/${date})"
fi
