#!/usr/bin/env bash

dir=/tmp/vim-anywhere
file="${dir}"/doc-"$( date +"%y%m%d%H%M%S")"
[[ -d "$dir" ]] || mkdir -p /tmp/vim-anywhere

touch "$file"
nvim-qt "$file"
xclip -in -rmlastnl -selection clipboard < "$file"

# vim: ft=sh
